singly_linked_list:
	gcc testing_singly_linked_list.c ds_custom_tests.c ../data_structures/singly_linked_list.c -o testing_singly_linked_list

doubly_linked_list:
	gcc testing_doubly_linked_list.c ds_custom_tests.c ../data_structures/doubly_linked_list.c -o testing_singly_linked_list

clean:
	rm *.exe