linear_search:
	gcc testing_linear_search.c custom_tests.c ../algorithms/linear_search.c -o testing_linear_search

binary_search:
	gcc testing_binary_search.c custom_tests.c ../algorithms/binary_search.c -o testing_binary_search

selection_sort:
	gcc testing_selection_sort.c custom_tests.c ../algorithms/selection_sort.c -o testing_selection_sort

bubble_sort:
	gcc testing_bubble_sort.c custom_tests.c ../algorithms/bubble_sort.c -o testing_bubble_sort

merge_sort:
	gcc testing_merge_sort.c custom_tests.c ../algorithms/merge_sort.c -o testing_merge_sort

interpolation_search:
	gcc testing_interpolation_search.c custom_tests.c ../algorithms/interpolation_search.c -o testing_interpolation_search

quick_sort:
	gcc testing_quick_sort.c custom_tests.c ../algorithms/quick_sort.c -o testing_quick_sort

insertion_sort:
	gcc testing_insertion_sort.c custom_tests.c ../algorithms/insertion_sort.c -o testing_insertion_sort

clean:
	rm *.exe